---
- name: Add postgres repo key
  ansible.builtin.apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: Create the repository for posgresql on ubuntu 20.04
  ansible.builtin.copy:
    src: pgdg.list
    dest: /etc/apt/sources.list.d/
    mode: '0644'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '20'

- name: Create the repository for posgresql on ubuntu 22.04
  ansible.builtin.copy:
    src: pgdg22_04.list
    dest: /etc/apt/sources.list.d/pgdg.list
    mode: '0644'
  when: ansible_distribution == "Ubuntu" and ansible_distribution_major_version == '22'

- name: Setup postgresql-11
  ansible.builtin.apt:
    pkg:
      - postgresql-11     # contrib no longer needed since 10 and higher
      - python3-psycopg2
    update_cache: yes

- name: Copy pg_hba.conf configuration
  ansible.builtin.copy:
    src: pg_hba.conf
    owner: postgres
    group: postgres
    dest: /etc/postgresql/11/main/pg_hba.conf
    mode: '0644'
  notify: "restart postgresql"

- name: Copy postgresql.conf configuration
  ansible.builtin.copy:
    src: postgresql.conf.debian
    owner: postgres
    group: postgres
    dest: /etc/postgresql/11/main/postgresql.conf
    mode: '0644'
  notify: "restart postgresql"

- name: Start and enable Postgres (at boot time)
  ansible.builtin.systemd:
    name: postgresql
    state: started
    enabled: yes
