---
- name: Upgrade molgenis to 10.x.y
  hosts: "{{ host_group }}"
  gather_facts: true
  become: true
  vars:
    host_group: "all"
    molgenis:
      setup: true
      version: 10.1.0

  tasks:
    - name: Gathering package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Clear versionlocks
      ansible.builtin.command: yum versionlock clear
      args:
        warn: false        # set warn=false to prevent warning about better using yum module
      changed_when: false
      when:
        - war_version.stat.isreg is not defined
        - ansible_os_family == 'RedHat'

    - name: Check if war of correct version is present
      ansible.builtin.stat:
        path: /usr/local/share/molgenis/war/molgenis-app-{{ molgenis.version }}.war
      register: war_version

    - name: Stop tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: stopped
      when: war_version.stat.isreg is not defined

    - name: Remove elastic indexes before upgrade to elastic 7
      ansible.builtin.uri:
        url: http://localhost:9200/*
        method: DELETE
      when: war_version.stat.isreg is not defined

    - name: Stop elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        state: stopped
      when: war_version.stat.isreg is not defined

    - name: Remove elastic indexes files
      ansible.builtin.file:
        state: absent
        path: "/var/lib/elasticsearch/nodes"
      when: war_version.stat.isreg is not defined

    - name: Remove old elastic 5.6 rpm
      ansible.builtin.yum:
        state: absent
        name: elasticsearch
      when:
        - war_version.stat.isreg is not defined
        - ansible_os_family == 'RedHat'

    - name: Purge old elastic 5.6 package
      ansible.builtin.apt:
        state: absent
        purge: yes
        name: elasticsearch
      when:
        - war_version.stat.isreg is not defined
        - ansible_os_family == 'Debian'

    - name: Remove elastic jvm.options in debian/ubuntu
      ansible.builtin.file:
        state: absent
        path: "/etc/elasticsearch/jvm.options"
      when:
        - war_version.stat.isreg is not defined
        - ansible_os_family == 'Debian'

    - name: Elasticsearch7 role
      ansible.builtin.include_role:
        name: elasticsearch_7
      when: war_version.stat.isreg is not defined

    - name: Remove old molgenis war folder
      ansible.builtin.file:
        path: /usr/local/share/molgenis/war
        state: absent
      when: war_version.stat.isreg is not defined

    - name: Create empty molgenis war folder
      ansible.builtin.file:
        path: /usr/local/share/molgenis/war
        state: directory
        owner: molgenis
        group: molgenis
        mode: '0775'
      when: war_version.stat.isreg is not defined

    - name: Install war MOLGENIS
      ansible.builtin.get_url:
        url: >
          https://registry.molgenis.org/repository/maven-public/org/molgenis/molgenis-app/{{
           molgenis.version }}/molgenis-app-{{ molgenis.version }}.war
        mode: '0660'
        owner: molgenis
        group: molgenis
        dest: /usr/local/share/molgenis/war/
      when: war_version.stat.isreg is not defined

    - name: Create symbolic link
      ansible.builtin.file:
        src: /usr/local/share/molgenis/war/molgenis-app-{{ molgenis.version }}.war
        dest: /usr/share/tomcat/webapps/ROOT.war
        owner: molgenis
        group: molgenis
        state: link
      when: war_version.stat.isreg is not defined

    - name: Start elasticsearch
      ansible.builtin.systemd:
        name: elasticsearch
        state: started
      when: war_version.stat.isreg is not defined

    - name: Start tomcat
      ansible.builtin.systemd:
        name: tomcat
        state: started
      when: war_version.stat.isreg is not defined

    - name: NodeJs role
      ansible.builtin.include_role:
        name: nodejs
      when: war_version.stat.isreg is not defined

    - name: Nginx role
      ansible.builtin.include_role:
        name: nginx
      when: war_version.stat.isreg is not defined
