---
- name: Python based on OS
  include_tasks: "{{ ansible_os_family|lower }}.yml"

- name: Install molgenis-py-client
  ansible.builtin.pip:
    executable: /usr/bin/pip3
    name: molgenis-py-client
