---
galaxy_info:
  role_name: minio
  author: Sido Haakma
  description: Minio file storage, used to get data into the federated platform
  company: MOLGENIS
  license: LGPL
  min_ansible_version: 2.7.9
  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - "focal"
        - "jammy"
  galaxy_tags: [molgenis]
dependencies: []
