---
- name: NginX based on OS
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Start and enable nginx (at boot time)
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Add in memory robots.txt to nginx
  ansible.builtin.copy:
    src: robots.conf
    dest: /etc/nginx/default.d/robots.conf
    mode: '0644'
  notify: "restart nginx"

- name: Ammend /etc/hosts to include hostname
  ansible.builtin.lineinfile:
    dest: /etc/hosts
    line: "{{ ansible_default_ipv4.address }} {{ inventory_hostname }}"
    state: present

- name: Install molgenis frontends local config
  ansible.builtin.copy:
    src: molgenis.conf
    dest: /etc/nginx/default.d/
    mode: '0644'
  notify: "restart nginx"
  when: molgenis.version is version('10.0.0', '>=')

- name: Register project from molgenis-server.properties
  ansible.builtin.shell:
    cmd: grep project /usr/local/share/molgenis/molgenis-server.properties | cut -d'=' -f2
  changed_when: false
  register: project_name
