---
galaxy_info:
  role_name: nodejs
  author: Erik Schaberg
  description: this role is part of the Molgenis installation
  company: UMCG/RUG
  license: license (GPLv3)
  min_ansible_version: 2.7.9
  platforms:
    - name: EL
      versions:
        - "8"
        - "7"
    - name: Ubuntu
      versions:
        - "focal"
        - "jammy"
  galaxy_tags: [molgenis]
dependencies: []
