---
- name: Stop systemd services | Cleanup
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: stopped
    daemon_reload: true
  with_items:
    - "{{ packages }}"

- name: Remove systemd services | Cleanup
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}.service"
    state: absent
  with_items:
    - "{{ packages }}"

- name: Remove configuration directories | Cleanup
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /etc/default/minio
    - /etc/armadillo
    - /etc/rserver

- name: Remove configuration directories | Cleanup
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - /usr/share/armadillo
    - /usr/local/bin/minio

- name: Remove package dependencies | Cleanup
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"
