---
- name: Setup new java-17
  ansible.builtin.apt:
    pkg:
      - openjdk-17-jre-headless
    update_cache: yes
  when: molgenis.version is version('9.1.0', '>=')

- name: Create extra symlink for JAVA_HOME
  ansible.builtin.file:
    src: /usr/lib/jvm/java-17-openjdk-amd64
    dest: /usr/lib/jvm/java-17-openjdk
    state: link
  when: molgenis.version is version('9.1.0', '>=')
