---
- name: Pre-install based on OS
  ansible.builtin.include_tasks: "{{ ansible_os_family | lower }}.yml"

- name: Create molgenis group
  ansible.builtin.group:
    name: molgenis

- name: Create tomcat uid
  ansible.builtin.user:
    name: tomcat
    group: molgenis
    shell: /bin/false

- name: Register if tomcat is already there
  ansible.builtin.stat:
    path: /usr/share/apache-tomcat-{{ tomcat_version }}/
  register: tomcat_already_there

- name: Install Tomcat from source
  ansible.builtin.unarchive:
    src: "https://archive.apache.org/dist/tomcat/tomcat-9/v{{ tomcat_version }}/bin/apache-tomcat-{{ tomcat_version }}.tar.gz"
    dest: "/usr/share/"
    owner: tomcat
    group: molgenis
    copy: no
  when: not tomcat_already_there.stat.exists

- name: Register if first install tomcat
  ansible.builtin.stat:
    path: /usr/share/apache-tomcat-{{ tomcat_version }}/webapps/examples
  register: tomcat_first_install

- name: Delete default folders tomcat webapps directory
  ansible.builtin.file:
    state: absent
    path: "/usr/share/apache-tomcat-{{ tomcat_version }}/webapps/{{ item }}"
  with_items:
    - ROOT
    - docs
    - examples
    - host-manager
    - manager
  when: tomcat_first_install.stat.exists

- name: Create softlink to tomcat logs
  ansible.builtin.file:
    src: /usr/share/apache-tomcat-{{ tomcat_version }}/logs
    dest: /var/log/tomcat
    state: link

- name: Create softlink to tomcat conf
  ansible.builtin.file:
    src: /usr/share/apache-tomcat-{{ tomcat_version }}/conf
    dest: /etc/tomcat
    state: link

- name: Create softlink to tomcat shortname
  ansible.builtin.file:
    src: /usr/share/apache-tomcat-{{ tomcat_version }}
    dest: /usr/share/tomcat
    state: link

- name: Install molgenis server.xml file for tomcat
  ansible.builtin.copy:
    src: server.xml
    dest: /usr/share/apache-tomcat-{{ tomcat_version }}/conf/server.xml
    mode: '0644'

- name: Install systemctl services file for tomcat
  ansible.builtin.template:
    src: tomcat.service_debian.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 512
    maxmem: 1024
  when:
    - memory == '4'
    - ansible_os_family == 'Debian'
  notify: "restart tomcat"

- name: Install systemctl services file for tomcat on large 8Gb VM
  ansible.builtin.template:
    src: tomcat.service_debian.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 512
    maxmem: 2048
    home: '/usr/lib/jvm/java-11-openjdk'
  when:
    - memory == '8'
    - ansible_os_family == 'Debian'
  notify: "restart tomcat"

- name: Install systemctl services file for tomcat on very large 16Gb VM
  ansible.builtin.template:
    src: tomcat.service_debian.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 1024
    maxmem: 4098
  when:
    - memory == '16'
    - ansible_os_family == 'Debian'
  notify: "restart tomcat"

- name: Install systemctl services file for tomcat
  ansible.builtin.template:
    src: tomcat.service_redhat_rocky.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 512
    maxmem: 1024
  when:
    - memory == '4'
    - ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  notify: "restart tomcat"

- name: Install systemctl services file for tomcat on large 8Gb VM
  ansible.builtin.template:
    src: tomcat.service_redhat_rocky.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 512
    maxmem: 2048
  when:
    - memory == '8'
    - ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  notify: "restart tomcat"

- name: Install systemctl services file for tomcat on very large 16Gb VM
  ansible.builtin.template:
    src: tomcat.service_redhat_rocky.j2
    dest: /etc/systemd/system/tomcat.service
    mode: '0644'
  vars:
    minmem: 1024
    maxmem: 4098
  when:
    - memory == '16'
    - ( ansible_os_family == 'RedHat' or ansible_os_family == 'Rocky' )
  notify: "restart tomcat"

- name: Enable Tomcat (at boot time)
  ansible.builtin.systemd:
    name: tomcat
    enabled: yes
    masked: no
    daemon_reload: yes
