---
- name: Import oracle rpm key
  ansible.builtin.rpm_key:
    state: present
    key: https://yum.oracle.com/RPM-GPG-KEY-oracle-ol7
  when: molgenis.version is version('9.1.0', '>=')

- name: Install JDK-17
  ansible.builtin.yum:
    name: https://download.oracle.com/java/17/latest/jdk-17_linux-x64_bin.rpm
    state: present
    disable_gpg_check: yes
  when: molgenis.version is version('9.1.0', '>=')
