---
- name: Setup new java-11
  ansible.builtin.apt:
    pkg:
      - openjdk-11-jdk-headless
    update_cache: yes

- name: Create extra symlink for JAVA_HOME
  ansible.builtin.file:
    src: /usr/lib/jvm/java-11-openjdk-amd64
    dest: /usr/lib/jvm/java-11-openjdk
    state: link
