---
- name: Install base packages used to configure CentOS properly
  ansible.builtin.yum:
    state: present
    name:
      - redhat-lsb-core
      - selinux-policy
      - selinux-policy-targeted
      - epel-release
      - nano
      - sudo
      - rsync
      - lsof
      - wget
      - chrony
      - openssh-server
      - yum-plugin-versionlock
      - audit
      - glibc-common
      - which
      - net-tools
      - bind-utils
      - dnf
      - java-11-openjdk-headless

- name: Create extra symlink for JAVA_HOME
  ansible.builtin.file:
    src: /etc/alternatives/jre_11
    dest: /usr/lib/jvm/java-11-openjdk
    state: link

- name: Gathering package facts
  ansible.builtin.package_facts:
    manager: auto

- name: Clear versionlocks
  ansible.builtin.command: yum versionlock clear
  args:
    warn: false        # set warn=false to prevent warning about better using yum module
  changed_when: false

- name: Install a ntpd/chronyd when needed
  ansible.builtin.systemd:
    state: started
    enabled: yes
    name: chronyd

- name: Initial sync of NTP/chronyc
  ansible.builtin.command: chronyc -a makestep
  changed_when: false

- name: Enable selinux
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
