# required
namespace: molgenis

name: armadillo

version: 2.0.4

readme: README.md

authors:
- Sido Haakma <s.haakma@rug.nl>

# optional
description: Armadillo is a service which can be used to perform federated analysis

license:
- LGPL-2.0-or-later

tags: [federation]

repository: https://github.com/molgenis/molgenis-service-armadillo

documentation: https://github.com/molgenis/molgenis-service-armadillo

homepage: https://molgenis.org

issues: https://github.com/molgenis/molgenis-service-armadillo/issues
