---
- hosts: all # needs to be: 'localhost' if local connection is set
  become: true
  # connection: local 
  become_user: root
    collections:
    - community.general
    - molgenis.armadillo
  gather_facts: true

  roles:
    - role: tools_migrate
      vars:
        users:
          # - { source_user: firstname.givenname, target_user: user-298371298312 }
          # - { source_user: firstname.givenname, target_user: user-987348932734 }