---
- name: Configure cronjob | Configuration
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"
  when: enabled

- name: Install cronjob for automatic upgrades | Configuration
  ansible.builtin.cron:
    name: "Upgrade Armadillo stack"
    minute: "1"
    hour: "0"
    weekday: "0"
    job: "/usr/share/armadillo/upgrade-armadillo.bash"
  when: enabled
