---
- name: Prepare environment | Configuration
  ansible.builtin.include_tasks: "{{ ansible_distribution | lower }}.yml"

- name: Add epel-release repo key | Configuration
  ansible.builtin.rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}

- name: Add epel-release | Installation
  ansible.builtin.dnf:
    state: present
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm

- name: Podman | Installation
  ansible.builtin.dnf:
    state: present
    name:
      - podman
      - podman-docker
      - podman-plugins
      - container-selinux

- name: Podman logging | Configuration
  ansible.builtin.copy:
    src: 40-docker.conf
    dest: /etc/rsyslog.d
    mode: '0644'
